tune_mm_mlp_adapter: True
vision_tower: openai/clip-vit-large-patch14-336
mm_vision_select_layer: -2
mm_projector_type: mlp2x_gelu
mm_use_im_start_end: False
mm_use_im_patch_token: False
pretrain_mm_mlp_adapter: ./checkpoints/llava-v1.5-13b-pretrain/mm_projector.bin